// <auto-generated />
using System;
using Api4u.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api4u.Migrations
{
    [DbContext(typeof(ToonsContext))]
    [Migration("20200501205604_Hospital")]
    partial class Hospital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api4u.Models.Athletics.Athlete", b =>
                {
                    b.Property<int>("AthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AthleteId");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            AthleteId = 1,
                            CompetitionId = 1,
                            Country = "USA",
                            DateOfBirth = new DateTime(1996, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christian",
                            LastName = "Coleman"
                        },
                        new
                        {
                            AthleteId = 2,
                            CompetitionId = 1,
                            Country = "GBR",
                            DateOfBirth = new DateTime(1995, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zharnel",
                            LastName = "Hughes"
                        },
                        new
                        {
                            AthleteId = 3,
                            CompetitionId = 6,
                            Country = "KEN",
                            DateOfBirth = new DateTime(1994, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brigid",
                            LastName = "Kosgei"
                        },
                        new
                        {
                            AthleteId = 4,
                            CompetitionId = 6,
                            Country = "ETH",
                            DateOfBirth = new DateTime(1990, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Worknesh",
                            LastName = "Degefa"
                        },
                        new
                        {
                            AthleteId = 5,
                            CompetitionId = 7,
                            Country = "ETH",
                            DateOfBirth = new DateTime(1994, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Birhanu",
                            LastName = "Legese"
                        },
                        new
                        {
                            AthleteId = 6,
                            CompetitionId = 7,
                            Country = "KEN",
                            DateOfBirth = new DateTime(1988, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lawrence",
                            LastName = "Cherono"
                        },
                        new
                        {
                            AthleteId = 7,
                            CompetitionId = 2,
                            Country = "SWE",
                            DateOfBirth = new DateTime(1999, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Armand",
                            LastName = "Duplantis"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Athletics.Competition", b =>
                {
                    b.Property<int>("CompetitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompetitionId");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            CompetitionId = 1,
                            EventName = "Men's 100m"
                        },
                        new
                        {
                            CompetitionId = 2,
                            EventName = "Men's Pole Vault"
                        },
                        new
                        {
                            CompetitionId = 3,
                            EventName = "Men's 50km Race Walking"
                        },
                        new
                        {
                            CompetitionId = 4,
                            EventName = "Women's 100m"
                        },
                        new
                        {
                            CompetitionId = 5,
                            EventName = "Women's 100m"
                        },
                        new
                        {
                            CompetitionId = 6,
                            EventName = "Women's Marathon"
                        },
                        new
                        {
                            CompetitionId = 7,
                            EventName = "Men's Marathon"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Countries.City", b =>
                {
                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("CityName");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityName = "Los Angeles",
                            ProvinceId = 2
                        },
                        new
                        {
                            CityName = "San Francisco",
                            ProvinceId = 2
                        },
                        new
                        {
                            CityName = "San Diego",
                            ProvinceId = 2
                        },
                        new
                        {
                            CityName = "Xiamen",
                            ProvinceId = 4
                        },
                        new
                        {
                            CityName = "Quanzhou",
                            ProvinceId = 4
                        },
                        new
                        {
                            CityName = "Ottawa",
                            ProvinceId = 6
                        },
                        new
                        {
                            CityName = "Windsor",
                            ProvinceId = 6
                        },
                        new
                        {
                            CityName = "Kingston",
                            ProvinceId = 6
                        },
                        new
                        {
                            CityName = "Mississauga",
                            ProvinceId = 6
                        },
                        new
                        {
                            CityName = "Hamilton",
                            ProvinceId = 6
                        });
                });

            modelBuilder.Entity("Api4u.Models.Countries.Continent", b =>
                {
                    b.Property<string>("ContinentName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ContinentName");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            ContinentName = "Africa"
                        },
                        new
                        {
                            ContinentName = "Asia"
                        },
                        new
                        {
                            ContinentName = "Europe"
                        },
                        new
                        {
                            ContinentName = "South America"
                        },
                        new
                        {
                            ContinentName = "Australia"
                        },
                        new
                        {
                            ContinentName = "North America"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Countries.Country", b =>
                {
                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AreaSqKm")
                        .HasColumnType("int");

                    b.Property<string>("CapitalCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContinentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryName");

                    b.HasIndex("ContinentName");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryName = "Canada",
                            AreaSqKm = 9976140,
                            CapitalCity = "Ottawa",
                            ContinentName = "North America"
                        },
                        new
                        {
                            CountryName = "USA",
                            AreaSqKm = 9629091,
                            CapitalCity = "Washington DC",
                            ContinentName = "North America"
                        },
                        new
                        {
                            CountryName = "Brazil",
                            AreaSqKm = 8511965,
                            CapitalCity = "Brasilia",
                            ContinentName = "South America"
                        },
                        new
                        {
                            CountryName = "India",
                            AreaSqKm = 3287590,
                            CapitalCity = "New Delhi",
                            ContinentName = "Asia"
                        },
                        new
                        {
                            CountryName = "China",
                            AreaSqKm = 9596960,
                            CapitalCity = "Beijing",
                            ContinentName = "Asia"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Countries.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CapitalCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryName");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            CapitalCity = "Montgomery",
                            CountryName = "USA",
                            Name = "Aalabama"
                        },
                        new
                        {
                            ProvinceId = 2,
                            CapitalCity = "Sacramento",
                            CountryName = "USA",
                            Name = "California"
                        },
                        new
                        {
                            ProvinceId = 3,
                            CapitalCity = "Honolulu",
                            CountryName = "USA",
                            Name = "Hawaii"
                        },
                        new
                        {
                            ProvinceId = 4,
                            CapitalCity = "Fuzhou",
                            CountryName = "China",
                            Name = "Fujian"
                        },
                        new
                        {
                            ProvinceId = 5,
                            CapitalCity = "Wuhan",
                            CountryName = "China",
                            Name = "Hubei"
                        },
                        new
                        {
                            ProvinceId = 6,
                            CapitalCity = "Toronto",
                            CountryName = "Canada",
                            Name = "Ontario"
                        },
                        new
                        {
                            ProvinceId = 7,
                            CapitalCity = "Edmopnton",
                            CountryName = "Canada",
                            Name = "Alberta"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Courses.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = "COMP2910",
                            InstructorId = 1,
                            Name = "Project Management"
                        },
                        new
                        {
                            CourseId = "COMP3973",
                            InstructorId = 2,
                            Name = "ASP.NET"
                        },
                        new
                        {
                            CourseId = "COMP3717",
                            InstructorId = 3,
                            Name = "Android"
                        },
                        new
                        {
                            CourseId = "COMP1536",
                            InstructorId = 4,
                            Name = "HTML & CSS"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Courses.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            Email = "zhang.liu@qq.com",
                            FirstName = "Zhang",
                            LastName = "Liu"
                        },
                        new
                        {
                            InstructorId = 2,
                            Email = "jin.ling@123.com",
                            FirstName = "Jin",
                            LastName = "Ling"
                        },
                        new
                        {
                            InstructorId = 3,
                            Email = "sam.sun@gmail.com",
                            FirstName = "Sam",
                            LastName = "Sun"
                        },
                        new
                        {
                            InstructorId = 4,
                            Email = "ann.fox@outlook.com",
                            FirstName = "Ann",
                            LastName = "Fox"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Foods.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FoodCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("FoodId");

                    b.HasIndex("FoodCategoryId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            FoodCategoryId = 1,
                            Name = "Croissant",
                            Unit = "dozen",
                            UnitPrice = 9.98f
                        },
                        new
                        {
                            FoodId = 2,
                            FoodCategoryId = 3,
                            Name = "Carrots",
                            Unit = "lbs",
                            UnitPrice = 0.98f
                        },
                        new
                        {
                            FoodId = 3,
                            FoodCategoryId = 2,
                            Name = "Apples",
                            Unit = "lbs",
                            UnitPrice = 0.65f
                        });
                });

            modelBuilder.Entity("Api4u.Models.Foods.FoodCategory", b =>
                {
                    b.Property<int>("FoodCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodCategoryId");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            FoodCategoryId = 1,
                            Description = @"Bakery products, which include bread, rolls, 
                cookies, pies, pastries, and muffins, are usually prepared from flour 
                or meal derived from some form of grain. Bread, already a common 
                staple in prehistoric times, provides many nutrients in the human diet.",
                            Name = "Bakery"
                        },
                        new
                        {
                            FoodCategoryId = 2,
                            Description = @"The sweet 
                and fleshy product of a tree or other plant that contains seed 
                and can be eaten as food.",
                            Name = "Fruit"
                        },
                        new
                        {
                            FoodCategoryId = 3,
                            Description = @"A plant 
                or part of a plant used as food, typically as accompaniment to meat 
                or fish, such as a cabbage, potato, carrot, or bean.",
                            Name = "Vegetables"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Health.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalId");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            HospitalId = 1,
                            City = "Vancouver",
                            Country = "Canada",
                            Name = "St. Paul's Hospital",
                            Phone = "604-682-2344",
                            PostalCode = "V6Z 1Y6",
                            Province = "British Columbia",
                            Street = "1081 Burrard Street"
                        },
                        new
                        {
                            HospitalId = 2,
                            City = "Port Moody",
                            Country = "Canada",
                            Name = "Eagle Ridge Hospital",
                            Phone = "604-461-2022",
                            PostalCode = "V3H 3W9",
                            Province = "British Columbia",
                            Street = "475 Guildford Way"
                        },
                        new
                        {
                            HospitalId = 3,
                            City = "Vancouver",
                            Country = "Canada",
                            Name = "Vancouver General Hospital (VGH)",
                            Phone = "604-875-4111",
                            PostalCode = "V5Z 1M9",
                            Province = "British Columbia",
                            Street = "899 West 12th Avenue"
                        },
                        new
                        {
                            HospitalId = 4,
                            City = "Surrey",
                            Country = "Canada",
                            Name = "Surrey Memorial Hospital",
                            Phone = "604-581-2211",
                            PostalCode = "V3V 1Z2",
                            Province = "British Columbia",
                            Street = "13750 96th Avenue"
                        },
                        new
                        {
                            HospitalId = 5,
                            City = "New Westminster",
                            Country = "Canada",
                            Name = "Royal Columbian Hospital",
                            Phone = "604-520-4253",
                            PostalCode = "V3L 3W7",
                            Province = "British Columbia",
                            Street = "330 East Columbia Street"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Health.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dosage")
                        .HasColumnType("int");

                    b.Property<string>("DosageUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SicknessId")
                        .HasColumnType("int");

                    b.HasKey("MedicineId");

                    b.HasIndex("SicknessId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("Api4u.Models.Health.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.HasIndex("HospitalId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Api4u.Models.Health.Sickness", b =>
                {
                    b.Property<int>("SicknessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("SicknessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SicknessId");

                    b.HasIndex("PatientId");

                    b.ToTable("Sicknesses");
                });

            modelBuilder.Entity("Api4u.Models.Movies.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            FirstName = "Ben",
                            LastName = "Kingsley",
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 2,
                            FirstName = "John",
                            LastName = "Gielgud",
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 3,
                            FirstName = "Rohini",
                            LastName = "Hattangadi",
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 4,
                            FirstName = "Julie",
                            LastName = "Andrews",
                            MovieId = 2
                        },
                        new
                        {
                            ActorId = 5,
                            FirstName = "Christopher",
                            LastName = "Plummer",
                            MovieId = 2
                        },
                        new
                        {
                            ActorId = 6,
                            FirstName = "Audrey",
                            LastName = "Hepburn",
                            MovieId = 3
                        },
                        new
                        {
                            ActorId = 7,
                            FirstName = "Rex",
                            LastName = "Harrison",
                            MovieId = 3
                        });
                });

            modelBuilder.Entity("Api4u.Models.Movies.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DirectorFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectorLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            DirectorFirstName = "Richard",
                            DirectorLastName = "Attenborough",
                            Name = "Gandhi",
                            Rating = "PG",
                            Year = 1982
                        },
                        new
                        {
                            MovieId = 2,
                            DirectorFirstName = "Robert",
                            DirectorLastName = "Wise",
                            Name = "The Sound of Music",
                            Rating = "G",
                            Year = 196
                        },
                        new
                        {
                            MovieId = 3,
                            DirectorFirstName = "George",
                            DirectorLastName = "Cukor",
                            Name = "My Fair Lady",
                            Rating = "PG",
                            Year = 1964
                        },
                        new
                        {
                            MovieId = 4,
                            DirectorFirstName = "Walter",
                            DirectorLastName = "Lang",
                            Name = "The King and I",
                            Rating = "G",
                            Year = 1956
                        },
                        new
                        {
                            MovieId = 5,
                            DirectorFirstName = "Hugh",
                            DirectorLastName = "Hudson",
                            Name = "Chariots of Fire",
                            Rating = "PG",
                            Year = 1981
                        },
                        new
                        {
                            MovieId = 6,
                            DirectorFirstName = "Stanley",
                            DirectorLastName = "Kubrick",
                            Name = "Spartacus",
                            Rating = "PG",
                            Year = 1960
                        });
                });

            modelBuilder.Entity("Api4u.Models.Restaurants.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            Name = "Oven Baked Lasagna",
                            Price = 17.989999999999998,
                            RestaurantId = 1,
                            Size = "Regular"
                        },
                        new
                        {
                            MenuId = 2,
                            Name = "Spaghetti & Meatballs",
                            Price = 17.989999999999998,
                            RestaurantId = 1,
                            Size = "Regular"
                        },
                        new
                        {
                            MenuId = 3,
                            Name = "Seafood Fettuccine",
                            Price = 19.989999999999998,
                            RestaurantId = 1,
                            Size = "Regular"
                        },
                        new
                        {
                            MenuId = 4,
                            Name = "Barbecued Duck",
                            Price = 25.5,
                            RestaurantId = 2,
                            Size = "Regular"
                        },
                        new
                        {
                            MenuId = 5,
                            Name = "Roasted Pork",
                            Price = 9.75,
                            RestaurantId = 2,
                            Size = "Regular"
                        },
                        new
                        {
                            MenuId = 6,
                            Name = "Royal Hawaiian",
                            Price = 18.989999999999998,
                            RestaurantId = 3,
                            Size = "10 \" Small"
                        },
                        new
                        {
                            MenuId = 7,
                            Name = "Royal Hawaiian",
                            Price = 27.989999999999998,
                            RestaurantId = 3,
                            Size = "13 \" Medium"
                        },
                        new
                        {
                            MenuId = 8,
                            Name = "Chicken Tikka",
                            Price = 4.9900000000000002,
                            RestaurantId = 4,
                            Size = "Regular"
                        },
                        new
                        {
                            MenuId = 9,
                            Name = "Butter Chicken",
                            Price = 12.99,
                            RestaurantId = 4,
                            Size = "Regular"
                        },
                        new
                        {
                            MenuId = 10,
                            Name = "Lamb Souvlaki",
                            Price = 19.0,
                            RestaurantId = 5,
                            Size = "Regular"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Restaurants.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            City = "Coquitlam",
                            Country = "Canada",
                            FoodType = "Western Food",
                            PostalCode = "V5G 1U8",
                            Province = "British Columbia",
                            RestaurantName = "White Spot",
                            Street = "1096 Lougheed Highway"
                        },
                        new
                        {
                            RestaurantId = 2,
                            City = "Coquitlam",
                            Country = "Canada",
                            FoodType = "Chinese Food",
                            PostalCode = "V6A 1C5",
                            Province = "British Columbia",
                            RestaurantName = "Hons",
                            Street = "310-3025 Lougheed Highway"
                        },
                        new
                        {
                            RestaurantId = 3,
                            City = "Port Coquitlam",
                            Country = "Canada",
                            FoodType = "Western Food",
                            PostalCode = "V3B 8A4",
                            Province = "British Columbia",
                            RestaurantName = "Boston Pizza",
                            Street = "300 - 2325 Ottawa Street"
                        },
                        new
                        {
                            RestaurantId = 4,
                            City = "Maple Ridge",
                            Country = "Canada",
                            FoodType = "Indian Food",
                            PostalCode = "V2X 1X6",
                            Province = "British Columbia",
                            RestaurantName = "Maple Leaf Indian Cuisine",
                            Street = "11956 207 Street"
                        },
                        new
                        {
                            RestaurantId = 5,
                            City = "Maple Ridge",
                            Country = "Canada",
                            FoodType = "Greek Food",
                            PostalCode = "V2X 2P9",
                            Province = "British Columbia",
                            RestaurantName = "Socrates Grill",
                            Street = "20691 Lougheed Hwy #19"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Species.Organism", b =>
                {
                    b.Property<int>("OrganismId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrganismId");

                    b.HasIndex("SpecieName");

                    b.ToTable("Organisms");

                    b.HasData(
                        new
                        {
                            OrganismId = 1,
                            Name = "Australian brush turkey",
                            SpecieName = "Bird"
                        },
                        new
                        {
                            OrganismId = 2,
                            Name = "Egyptian plover",
                            SpecieName = "Bird"
                        },
                        new
                        {
                            OrganismId = 3,
                            Name = "White stork",
                            SpecieName = "Bird"
                        },
                        new
                        {
                            OrganismId = 4,
                            Name = "Kingfisher",
                            SpecieName = "Bird"
                        },
                        new
                        {
                            OrganismId = 5,
                            Name = "Atlantic salmon",
                            SpecieName = "Fish"
                        },
                        new
                        {
                            OrganismId = 6,
                            Name = "Great white shark",
                            SpecieName = "Fish"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Species.Specie", b =>
                {
                    b.Property<string>("SpecieName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SpecieName");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            SpecieName = "Bird"
                        },
                        new
                        {
                            SpecieName = "Mammal"
                        },
                        new
                        {
                            SpecieName = "Insect"
                        },
                        new
                        {
                            SpecieName = "Reptile"
                        },
                        new
                        {
                            SpecieName = "Fish"
                        },
                        new
                        {
                            SpecieName = "Amphibians"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Sports.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamName");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            FirstName = "Bob",
                            LastName = "Fox",
                            Position = "Forward",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 2,
                            FirstName = "Sam",
                            LastName = "Dix",
                            Position = "Left Wing",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 3,
                            FirstName = "John",
                            LastName = "Rooster",
                            Position = "Right Wing",
                            TeamName = "Flames"
                        },
                        new
                        {
                            PlayerId = 4,
                            FirstName = "Pat",
                            LastName = "Plumber",
                            Position = "Defense",
                            TeamName = "Oilers"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Sports.Team", b =>
                {
                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamName");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamName = "Canucks",
                            City = "Vancouver",
                            Country = "Canada",
                            Province = "BC"
                        },
                        new
                        {
                            TeamName = "Sharks",
                            City = "San Jose",
                            Country = "USA",
                            Province = "CA"
                        },
                        new
                        {
                            TeamName = "Oilers",
                            City = "Edmonton",
                            Country = "Canada",
                            Province = "AB"
                        },
                        new
                        {
                            TeamName = "Flames",
                            City = "Calgary",
                            Country = "Canada",
                            Province = "AB"
                        },
                        new
                        {
                            TeamName = "Ducks",
                            City = "Anaheim",
                            Country = "USA",
                            Province = "CA"
                        },
                        new
                        {
                            TeamName = "Lightening",
                            City = "Tampa Bay",
                            Country = "USA",
                            Province = "FL"
                        },
                        new
                        {
                            TeamName = "Blackhawks",
                            City = "Chicago",
                            Country = "USA",
                            Province = "IL"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Students.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Api4u.Models.Toons.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Api4u.Models.Vehicles.Vehicle", b =>
                {
                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleManufacturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Model");

                    b.HasIndex("VehicleManufacturerName");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Model = "Corolla",
                            Fuel = "Gas",
                            Type = "Sedan",
                            VehicleManufacturerName = "Toyota"
                        },
                        new
                        {
                            Model = "Rav4",
                            Fuel = "Gas",
                            Type = "SUV",
                            VehicleManufacturerName = "Toyota"
                        },
                        new
                        {
                            Model = "Soul",
                            Fuel = "Electric",
                            Type = "SUV",
                            VehicleManufacturerName = "Kia"
                        },
                        new
                        {
                            Model = "Model S",
                            Fuel = "Electric",
                            Type = "Sedan",
                            VehicleManufacturerName = "Tesla"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Vehicles.VehicleManufacturer", b =>
                {
                    b.Property<string>("VehicleManufacturerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleManufacturerName");

                    b.ToTable("VehicleManufacturers");

                    b.HasData(
                        new
                        {
                            VehicleManufacturerName = "Toyota",
                            Country = "Japan"
                        },
                        new
                        {
                            VehicleManufacturerName = "Kia",
                            Country = "South Korea"
                        },
                        new
                        {
                            VehicleManufacturerName = "Renault",
                            Country = "France"
                        },
                        new
                        {
                            VehicleManufacturerName = "Mercedes",
                            Country = "Germany"
                        },
                        new
                        {
                            VehicleManufacturerName = "Tesla",
                            Country = "USA"
                        });
                });

            modelBuilder.Entity("Api4u.Models.Athletics.Athlete", b =>
                {
                    b.HasOne("Api4u.Models.Athletics.Competition", "Competition")
                        .WithMany("Athletes")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Countries.City", b =>
                {
                    b.HasOne("Api4u.Models.Countries.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Countries.Country", b =>
                {
                    b.HasOne("Api4u.Models.Countries.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Countries.Province", b =>
                {
                    b.HasOne("Api4u.Models.Countries.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Courses.Course", b =>
                {
                    b.HasOne("Api4u.Models.Courses.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Foods.Food", b =>
                {
                    b.HasOne("Api4u.Models.Foods.FoodCategory", "FoodCategory")
                        .WithMany("Foods")
                        .HasForeignKey("FoodCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Health.Medicine", b =>
                {
                    b.HasOne("Api4u.Models.Health.Sickness", "Sickness")
                        .WithMany("Medicines")
                        .HasForeignKey("SicknessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Health.Patient", b =>
                {
                    b.HasOne("Api4u.Models.Health.Hospital", "Hospital")
                        .WithMany("Patients")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Health.Sickness", b =>
                {
                    b.HasOne("Api4u.Models.Health.Patient", "Patient")
                        .WithMany("Sicknesses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Movies.Actor", b =>
                {
                    b.HasOne("Api4u.Models.Movies.Movie", "Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Restaurants.Menu", b =>
                {
                    b.HasOne("Api4u.Models.Restaurants.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Species.Organism", b =>
                {
                    b.HasOne("Api4u.Models.Species.Specie", "Specie")
                        .WithMany("Organisms")
                        .HasForeignKey("SpecieName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api4u.Models.Sports.Player", b =>
                {
                    b.HasOne("Api4u.Models.Sports.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamName");
                });

            modelBuilder.Entity("Api4u.Models.Vehicles.Vehicle", b =>
                {
                    b.HasOne("Api4u.Models.Vehicles.VehicleManufacturer", "VehicleManufacturer")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleManufacturerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
